### PR TITLE
Oes56 kmz uploads

### PR DESCRIPTION
**Pull request by tparkergh**
Fixes several KML file issues by modifying the uploaded file. Refactor existing code out of service so it can be tested and the new fixes can be extended.

### CODE REVIEW

**Comment by comeara** [comment]
Ok, first two questions based on an initial read:

1. Why are there two public entry points to KmlFormatter? I see format() and fixCommonKmlIssues(). It appears the caller would never call one without the other.
1. Why manipulate the document content as a string with regular expressions? It seems like a risky approach that may or may not end up with a valid KML doc in the end.

Good job getting this under test.

Will keep reviewing.

**Comment by tparkergh** [comment]
The main issue is doing two passes to tweak the doc. The code is using an InputStream which make it difficult to search for errors since they can occur between different buffers. I'm using fixCommonKmlIssues() as a second pass where I can ensure I can find the errors. 

RegEx seemed like a decent option. I need to find missing tags that span several lines and hundreds of bytes. The coordinates can be VERY long.

I'm up for any suggestions on processing this one a single pass without loading the entire doc into memory using the InputStream.

**Comment by comeara** [comment]
Can you elaborate on "without loading the entire doc into memory using the InputStream" please?

**Comment by tparkergh** [comment]
That is a bad sentence. It would have been clear to say, I'd prefer to use a single pass with the ZipInputStream rather than loading the file into memory as a giant string.

**Comment by comeara** [comment]
I spent a little time experimenting yesterday I have 2 thoughts on this:

1. Your approach is pragmatic and that's a good thing
1. There are very powerful tools available to parse, validate and manipulate the DOM in Java

I think the question here is what kind of fix are we looking for? The scope of this fix is focused on particular KML issues but we could definitely still end up accepting a doc that won't display.

Alternatively, we could parse the document, validate it against the XML schema, apply fixes that we know are safe using dom manipulation or XSLT and write out a normalized file for storage. That would give us much more insight into validation issues and get closer to ensuring that every KML displays in the UI.

Let me know if you want to chat about it.

**Comment by tparkergh** [comment]
I agree completely, There all the errors are one offs and we won't have
them fixed until someone discovers it and reports it. All the conversations
to date is to support what Google earth is supporting. However Goggle earth
"fixes" several common issues on their side. There are several KML
generators that apparently pump out KML's that have various issues and they
currently have to import it into Google Earth and reexport it.

Non working files are of two categories: Invalid files not conforming to
the Schema, and unsupported features in the rendering library
(OpenLayers). My first thought was to do schema validation. But that
doesn't solve issues like the extra commas separating the coordinates that
is not defined by the schema.

I havn't thought about XSLT and not sure how it would fix a couple issues,
though it could fix the others. Then there KML files that point to remote
KML files. Obviously those ones wouldn't be fixed.

 Let's talk.

Thanks
Tom

**Pull request merged**
